# Generated by Django 4.1.2 on 2022-10-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Listing is active'),
        ),
    ]
