# Generated by Django 4.1.2 on 2022-10-17 14:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_legoseries_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0003_marketitem_created_marketitem_last_modified'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketitem',
            unique_together={('seller', 'lego_set')},
        ),
    ]
