# Generated by Django 4.1.2 on 2022-10-12 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegoSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='LegoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField(verbose_name='LEGO serial nubmer')),
                ('title', models.CharField(max_length=200, verbose_name='Set title')),
                ('n_details', models.PositiveIntegerField(verbose_name='Number of details')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.legoseries', verbose_name='LEGO series')),
            ],
            options={
                'unique_together': {('set_number', 'series', 'title')},
            },
        ),
    ]
