# Generated by Django 4.1.2 on 2022-10-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legoseries',
            old_name='title',
            new_name='name',
        ),
    ]
