# Generated by Django 4.1.2 on 2022-10-14 20:55

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_title_legoseries_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegoSetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.utils.lego_set_image_filepath, verbose_name='Image File')),
                ('lego_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.legoset')),
            ],
        ),
    ]
