# Generated by Django 4.1.2 on 2022-10-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_legosetimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legoseries',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
