# Generated by Django 4.1.2 on 2022-10-31 18:50

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_likedislike'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegocyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('avatar', models.ImageField(upload_to=core.utils.user_avatar_filepath, verbose_name='User avatar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
